image: fedora/31
packages:
  - wget
  - csh
  - git
  - gcc-c++
  - bison
  - flex
  - tcl-devel
  - readline-devel
  - gawk
  - libffi-devel
  - graphviz
  - pkg-config
  - python3
  - python3-devel
  - boost-devel
  - boost-python3-devel
  - zlib-devel
  - cmake
  - eigen3-devel
  - automake
  - autoconf
  - gperf
  - libyaml-devel
sources:
  - https://git.sr.ht/~macbook/gram
tasks:
  - install-python-packages: |
      pip install yowasp-yosys git+git://github.com/nmigen/nmigen.git git+git://github.com/nmigen/nmigen-boards.git git+git://github.com/nmigen/nmigen-stdio.git git+git://github.com/nmigen/nmigen-soc.git git+git://github.com/lambdaconcept/lambdasoc.git --user
  - install-icarus-verilog: |
      cd /tmp
      git clone git://github.com/steveicarus/iverilog.git
      cd iverilog
      autoconf
      ./configure
      make -j$(nproc)
      sudo make install
  - install-gram: |
      cd ~/gram
      python setup.py install --user
  - run-tests: |
      cd ~/gram
      contrib/test
