image: fedora/31
packages:
  - wget
  - csh
  - git
  - gcc-c++
  - bison
  - flex
  - tcl-devel
  - readline-devel
  - gawk
  - libffi-devel
  - graphviz
  - pkg-config
  - python3
  - python3-devel
  - boost-devel
  - boost-python3-devel
  - zlib-devel
  - cmake
  - eigen3-devel
  - automake
  - autoconf
  - gperf
  - libyaml-devel
  - gmp-devel
  - z3-devel
  - yices-devel
  - yices-tools
sources:
  - https://git.sr.ht/~macbook/gram
tasks:
  - install-python-packages: |
      pip install git+git://github.com/nmigen/nmigen.git git+git://github.com/nmigen/nmigen-boards.git git+git://github.com/nmigen/nmigen-stdio.git git+git://github.com/nmigen/nmigen-soc.git git+git://github.com/lambdaconcept/lambdasoc.git yowasp-yosys --user
      pip list
  - install-gram: |
      cd ~/gram
      python setup.py install --user
  - run-tests: |
      alias yosys=yowasp-yosys
      cd ~/gram
      export YOSYS=yowasp-yosys SBY=yowasp-sby SMTBMC=yowasp-yosys-smtbmc NMIGEN_USE_YOSYS=builtin
      contrib/test
shell: false
