image: fedora/31
packages:
  - wget
  - csh
  - git
  - gcc-c++
  - bison
  - flex
  - tcl-devel
  - readline-devel
  - gawk
  - libffi-devel
  - graphviz
  - pkg-config
  - python3
  - python3-devel
  - boost-devel
  - boost-python3-devel
  - zlib-devel
  - cmake
  - eigen3-devel
  - automake
  - autoconf
  - gperf
  - libyaml-devel
  - gmp-devel
  - z3-devel
  - yices-devel
  - yices-tools
sources:
  - https://git.sr.ht/~macbook/gram
tasks:
  - install-python-packages: |
      pip install git+git://github.com/nmigen/nmigen.git git+git://github.com/nmigen/nmigen-boards.git git+git://github.com/nmigen/nmigen-stdio.git git+git://github.com/nmigen/nmigen-soc.git git+git://github.com/lambdaconcept/lambdasoc.git --user
      pip list
  - install-yosys: |
      cd /tmp
      git clone https://github.com/YosysHQ/yosys yosys
      cd yosys
      echo "Yosys Git hash: $(git rev-parse HEAD)"
      make config-gcc
      make -j$(nproc)
      sudo make install
      rm -rf /tmp/yosys
  - install-symbiyosys: |
      cd /tmp
      git clone https://github.com/YosysHQ/SymbiYosys.git SymbiYosys
      cd SymbiYosys
      echo "SymbiYosys Git hash: $(git rev-parse HEAD)"
      sudo make install
      rm -rf /tmp/SymbiYosys
  - install-icarus-verilog: |
      cd /tmp
      git clone git://github.com/steveicarus/iverilog.git iverilog
      cd iverilog
      echo "Icarus Verilog Git hash: $(git rev-parse HEAD)"
      autoconf
      ./configure
      make -j$(nproc)
      sudo make install
      rm -rf /tmp/iverilog
  - install-gram: |
      cd ~/gram
      python setup.py install --user
  - run-tests: |
      cd ~/gram
      contrib/test
shell: false
